---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      memory: 1024
    network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
    - ["forwarded_port", {guest: 80, host: 8888}]

#  - name: ubuntu-12.04
#  - name: ubuntu-10.04
#  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[headwire::default]
    attributes:
  - name: teamserver
    run_list:
      - recipe[headwire::teamserver]
    attributes:
    excludes:
      - centos-6.4
  - name: logstash
    run_list:
      - recipe[headwire::logstash]
    attributes:

