source "https://api.berkshelf.com"

metadata

#cookbook "runit", path: '/home/kw/dev/ironfan-pantry/cookbooks/runit'
cookbook "logstash"
cookbook "redis"
cookbook "tomcat"
cookbook "gitlab", path: '/home/kw/dev/chef-repo/cookbooks/cookbook-gitlab'
